//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetStream_Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJSYXBoaSIsIm5iZiI6MTY3MTExNTEw" +
            "OSwiZXhwIjoxNjcxMTE2MDA5LCJpYXQiOjE2NzExMTUxMDl9.PVl460QBjqW35WIpgrFhgMeQAKn-DYo" +
            "8lj1psLdj49kWauvEWvJRVwxD-jJlxqJFDB7ULA6Y7S0sGP0XjokYKQ")]
        public string JWTToken {
            get {
                return ((string)(this["JWTToken"]));
            }
            set {
                this["JWTToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:7293")]
        public string APILink {
            get {
                return ((string)(this["APILink"]));
            }
            set {
                this["APILink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Registration")]
        public string registrationLink {
            get {
                return ((string)(this["registrationLink"]));
            }
            set {
                this["registrationLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-CH")]
        public string LanguageID {
            get {
                return ((string)(this["LanguageID"]));
            }
            set {
                this["LanguageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public string WindowsHeight {
            get {
                return ((string)(this["WindowsHeight"]));
            }
            set {
                this["WindowsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string WindowsWidth {
            get {
                return ((string)(this["WindowsWidth"]));
            }
            set {
                this["WindowsWidth"] = value;
            }
        }
    }
}
